# Generated by Django 4.0.5 on 2022-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('GRN', 'Grivna')], default='GRN', max_length=3),
        ),
    ]
